### ISSUE TITLE
add Rubygems

### ISSUE THREAD

**Issue by bino98** [alpaca-tc/active_record_bitmask#2]
:pray:

**Comment by alpaca-tc** [comment]
done

**Comment by bino98** [comment]
@alpaca-tc 
<img width="1125" alt="active_record_bitmask___RubyGems_org___コミュニティのGemホスティングサービス" src="https://user-images.githubusercontent.com/353699/72043274-18efd000-32f4-11ea-9b38-1a8d584720a4.png">
